### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Biloot** [JoeJoeTV/nemo-extension-kdeconnect#1]
I installed this extension successfully, and I paired my phone to my computer, but when I click on "Share with KDE" after right-clicking on a file, nothing happens ! I can't tell anything more, KDE works really well on my computer (I use notifications sharing above all) and I never had any problem !

Here are some specs :
> Distro : `Linux Mint 20.1 Cinnamon`
> Nemo version : `4.8.6`
> Kernel version : `5.4.0-122-generic`

**Comment by JoeJoeTV** [comment]
Did you use the deb file or just the tar.gz file for installation?

**Comment by Biloot** [comment]
The `.deb` one.

**Comment by JoeJoeTV** [comment]
I'll look into it, but I have a lot to do right now, so it's maybe going to take a while, but i'll send you instructions on how to get more info.
Simple Tests:
- Check that "KDECOnnectMenu+NemoPython" is showing in the Modules section in Nemo Settings.
- Close ALL Nemo windows and start nemo from the terminal with the command "nemo". Then, try right clicking on a file and click on the send to device option, even if it doesn't work. Then look in the output in the terminal and see if you see any obvoius errors that mention the extension

**Comment by Biloot** [comment]
I didn't check that, it was disabled! I just had to enable the module and then it worked! Sorry for the inconvenience and thanks a lot for your answers.
By the way, there are no errors at all when I launch Nemo from the terminal, your extension works great!
